// <auto-generated />
namespace Proj.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class UserName_And_Status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserName_And_Status));
        
        string IMigrationMetadata.Id
        {
            get { return "202109222122126_UserName_And_Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
