// <auto-generated />
namespace Proj.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Product_And_Phone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_And_Phone));
        
        string IMigrationMetadata.Id
        {
            get { return "202109232149276_Product_And_Phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
